# Generated by Django 3.2.8 on 2021-12-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giornalista',
            name='cognome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
